name: flutter_build_ipa_no_signin.yml

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    
    env:
      WORKING_DIR: log_poc

    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
        
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
        working-directory: ${{ env.WORKING_DIR }}

      - run: pod repo update
        working-directory: ${{ env.WORKING_DIR }}/ios

      - name: Build iOS app
        run: flutter build ios --release --no-codesign
        working-directory: ${{ env.WORKING_DIR }}

      - run: mkdir Payload
        working-directory: ${{ env.WORKING_DIR }}/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: ${{ env.WORKING_DIR }}/build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 log_poc.ipa Payload
        working-directory: ${{ env.WORKING_DIR }}/build/ios/iphoneos

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.WORKING_DIR }}/build/ios/iphoneos/log_poc.ipa
          tag: v${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ vars.PATCH_VERSION }}
          overwrite: true
          body: "Test release"

      # - name: Create archive
      #   run: |
      #     tar -czvf archive.tar.gz .

      # - name: Upload archive
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: repository-archive
      #     path: archive2.tar.gz
